config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pins#index'
  resources :pins

  resources :comments, only: %i[destroy]
  post ":commentable_type/:commentable_id/comment", to: "comments#create", as: :commentable_comment

  post ":object_type/:object_id/like", to: "likes#create", as: :like_object

  resources :categories,only: %i[index show destroy]

  resource :profile, only: %i[show]
  


end

app/models/pin.rb
class Pin < ApplicationRecord
    has_one_attached :image

    is_impressionable

    belongs_to :user
    has_many :comments, as: :commentable
    has_many :tags, dependent: :delete_all
    has_many :categories, through: :tags
    has_many :likes, as: :object

    validates :title, presence: true, length: { minimum: 3 }
    validates :caption, presence: true, length: { minimum: 5 }

    def category_names=(names)

        new_names = names.split(",").map{|name| name.downcase.strip}.uniq
        current_names = categories.map(&:name)
        old_names = current_names - new_names
        new_names = new_names - current_names
    
        old_category_ids = Category.where(name: old_names).ids
        tags.where(category_id: old_category_ids).delete_all if old_category_ids.present?
    
        new_names.each do |name|
          category = Category.find_or_create_by(name: name)
          categories << category
        end
      end
    
      def category_names
        categories.map(&:name).join(",")
      end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create update edit]
  before_action :pin, only: %i[ show edit update destroy ]
  impressionist :actions=>[:show,:index]
  # GET /pins or /pins.json
  def index
    @pins = Pin.all.with_attached_image.includes([:user,:categories])
    @q = params[:q]
    if @q
    titles = Arel::Table.new(:pins)[:title]
    @pins = @pins.where(titles.matches("%#{@q}%"))

    end
  end

  # GET /pins/1 or /pins/1.json
  def show
    @comments = pin.comments.includes(:user,:comments)
    impressionist(@pin)
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins or /pins.json
  def create
    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to pin_url(@pin), notice: "Pin was successfully created." }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1 or /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to pin_url(@pin), notice: "Pin was successfully updated." }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1 or /pins/1.json
  def destroy
    @pin.destroy

    respond_to do |format|
      format.html { redirect_to pins_url, notice: "Pin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def pin
      @pin = Pin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pin_params
      params.require(:pin).permit(:title, :caption, :image, :user_id, :category_names)
    end
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/pins/_form.html.erb
<%= form_with model: @pin, class:"m-5" do |form| %>
  <% if pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
        <% pin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, class:"form-label" %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="field">
    <%=form.label :tags, class:"form-label"%>
    <br>
      <%= form.text_field :category_names%>
  </div>
  
  <div class="field">
    <%= form.label :caption, class:"form-label"  %>
    <%= form.text_area :caption, class:"form-control"  %>
  </div>

   <div class="field">
    <%= form.label :image, class:"form-label"  %>
    <%= form.file_field :image, class:"form-control"  %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit nil, class:"btn btn-success" %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<div class="col-6">
  <div class="">
    <%=link_to image_tag(pin.image.variant(resize_to_limit: [300, 300])),pin_path(pin) if pin.image.attached? %>
  </div>
  <div class="">
    <%= link_to pin.title, pin_path(pin)%>
  </div>
  <span class="badge bg-secondary" title="Created"><%=pin.created_at%></span>
  <span class="badge bg-primary" title="Author"><%=pin.user.username%></span>
  <span class="badge bg-danger" title="Likes">
    <span class="like-counter">
      <%=pin.likes.size if pin.likes.size > 0%>
    </span>
    <a class="like" data-object-id="<%=pin.id%>">Like</a></span>
  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye-fill" viewBox="0 0 16 16">
    <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"/>
    <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"/>
  </svg>
  <%=pin.impressionist_count %>
  <div class="">
    <%pin.categories.each do |category|%>
      <span class="badge">
        <%=link_to category.name, category_path(category)%>
      </span>
    <%end%>
  </div>
</div>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form', pin: @pin %>

<%= link_to 'Show', @pin, class:"btn btn-secondary"   %> 
<%= link_to 'Back', pins_path, class:"btn btn-primary"  %>

app/views/pins/index.html.erb
<h1>Welcome</h1>
<hr>
<div class="row">
 <%= render @pins%>
<div>

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'form', pin: @pin %>

<%= link_to 'Back', pins_path, class:"btn btn-primary" %>

app/views/pins/show.html.erb
<%= turbo_stream_from "pin" %>
<p id="notice"><%= notice %></p>
<p>
  <strong>Title:</strong>
  <%= @pin.title %>
</p>
<%@pin.categories.each do |category|%>
  <span class="badge">
    <%=link_to category.name, category_path(category)%>
  </span>
<%end%>
<p>
  <strong>Caption:</strong>
  <%= @pin.caption %>
</p>
<p>
  <strong>Image:</strong>
  <% if @pin.image.attached? %>
    <%= image_tag @pin.image, width: "600px" %>
  <% end %>
</p>
<%= link_to 'Back', pins_path, class:"btn btn-primary" %>
<span class="likes">
  <%=@pin.likes.count%>
</span>
<%= link_to "Like","", class:"like"%>
</div>
<div class="">
  <%= link_to("Edit", edit_pin_path(@pin), class:"btn btn-warning") if user_signed_in? && current_user.id == @pin.user_id%>
  <%= link_to 'Delete', @pin, class:"btn btn-danger",method: :delete, data: { confirm: 'Are you sure?' }%>
  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye-fill" viewBox="0 0 16 16">
    <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"/>
    <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"/>
  </svg>
  <%= @pin.impressionist_count %>
  <h2>Comments:</h2>
  <div class="">
    <%= turbo_frame_tag "pin_#{@pin.id}_comments" do %>
      <%=render @comments%>
    <%end%>
  </div>
  <div class="">
    <%= render "comments/form", commentable:@pin%>
  </div>