config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pins#index'
  resources :pins

  resources :comments, only: %i[destroy]
  post ":commentable_type/:commentable_id/comment", to: "comments#create", as: :commentable_comment

  post ":object_type/:object_id/like", to: "likes#create", as: :like_object

  resources :categories,only: %i[index show destroy]

  resource :profile, only: %i[show]
  


end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable, dependent: :destroy

  validates :text, length: {minimum: 1}

  after_create_commit do
    broadcast_prepend_to "pin", target: object_broadcast_name
  end

  def object_broadcast_name
    "#{commentable_type.downcase}_#{commentable_id}_comments"
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!, only: %i[create destroy]

  def create
    @comment = current_user.comments.build(comment_paramas)
    @comment.commentable = commentable
    @comment.save

    return redirect_to(commentable) if commentable.class.name != "Comment"

    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.json { render json: @comment }
    end
  end

  def destroy
    if @comment = current_user.comments.find_by(id: params[:id])
      @comment.delete
      return redirect_back(fallback_location: root_path)
    end
  end

  private

  def commentable
    commentable_model.find(params[:commentable_id])
  end

  def commentable_model
    params[:commentable_type].constantize
  end

  def comment_paramas
    params.require(:comment).permit(:text,:user_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="">
  <div class="">
    <%=comment.text%>
  </div>
  <div class="">
    Author: <%=comment.user.username%> <%#=link_to "X",comment_path(comment), method: :delete, data: {confirm: "Yoy sure?"} if user_signed_in? && current_user == comment.user%>
    commented_at: <%=comment.created_at%>
    <div>
    </div>
    <div class="mx-3">
      <div class="">
        <%= turbo_frame_tag "comment_#{comment.id}_comments" do%>
          <%=render comment.comments%>
        <%end%>
      </div>
      <%= render "comments/form", commentable:comment%>
    </div>
  </div>

app/views/comments/_form.html.erb
<%= form_with model: Comment.new ,url: commentable_comment_path(commentable.class.name,commentable.id) do |f|%>
  <%=f.label :text%>
  <%=f.text_area :text %>

  <%=f.submit %>
<%end%>