config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pins#index'
  resources :pins

  resources :comments, only: %i[destroy]
  post ":commentable_type/:commentable_id/comment", to: "comments#create", as: :commentable_comment

  post ":object_type/:object_id/like", to: "likes#create", as: :like_object

  resources :categories,only: %i[index show destroy]

  resource :profile, only: %i[show]
  


end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-2">
  <div class="container-fluid">
    <a class="navbar-brand" href="/"><b>Pins<b></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to 'Create', new_pin_path, class:"btn btn-outline-primary" %>
              <%= link_to "Categories", categories_path, class:"btn btn-outline-info"%>
            </li>
          </ul>
          |
          <%=form_with url: pins_path, method: :get, class:"d-flex" do |f|%>
            <%=f.text_field :q, value: @q, placeholder: "Search",class:"form-control me-2"%>
            <%=f.submit "Search" ,class: "btn btn-outline-success"%>
          <%end%>
          |
          <div class="">
            <% if user_signed_in?%>
              <%=link_to "Profile", profile_path, class:"btn btn-outline-secondary"%>
              <%=link_to("Exit", destroy_user_session_path,method: :delete, class:"btn btn-outline-danger")%>
            <%else%>
              <%=link_to("Login", new_user_session_path, class:"btn btn-outline-primary") %>
            <%end%>
          </div>
        </div>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application'%>
  </head>
  <body>
    <%=render "layouts/navbar"%>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>